name: servant-rate-limit
version: 0.2.0.0
github: "mbg/wai-rate-limit"
license: MIT
license-file: LICENSE
author: "Michael B. Gale"
maintainer: "github@michael-gale.co.uk"
copyright: "Copyright (c) Michael B. Gale"

category: Security
synopsis: "Rate limiting for Servant"
description: "A Haskell library which implements rate limiting for Servant"

extra-source-files:
  - README.md
  - CHANGELOG.md

default-extensions:
  - DataKinds
  - FlexibleContexts
  - FlexibleInstances
  - MultiParamTypeClasses
  - OverloadedStrings
  - RecordWildCards
  - TypeApplications
  - TypeFamilies
  - TypeOperators

dependencies:
  - base >= 4.8 && < 5
  - bytestring
  - http-types < 1
  - servant
  - time-units >= 1.0 && < 2
  - time-units-types >= 0.2 && < 1
  - wai >= 3.0 && < 4
  - wai-rate-limit >= 0.3 && < 1

flags:
  server:
    description: Enable servant-server support.
    manual: true
    default: true
  client:
    description: Enable servant-client support.
    manual: true
    default: true

when:
  - condition: flag(server)
    dependencies:
      - servant-server
  - condition: flag(client)
    dependencies:
      - servant-client

library:
  source-dirs: src
  ghc-options:
    - -Wall
  when:
    - condition: flag(server)
      exposed-modules:
        - Servant.RateLimit.Server
    - condition: flag(client)
      exposed-modules:
        - Servant.RateLimit.Client

tests:
  servant-rate-limit-tests:
    source-dirs: test
    main: Spec.hs
    dependencies:
      - hedis
      - http-client
      - servant-client
      - servant-rate-limit
      - servant-server
      - tasty
      - tasty-hunit
      - wai-extra
      - wai-rate-limit-redis
      - warp
    when:
      condition: flag(server) && flag(client)
      then:
        buildable: true
      else:
        buildable: false
