name: Haskell

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/dependabot.yml"
      - "*.md"
      - "LICENSE"
  pull_request:

concurrency:
  group: haskell-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: "Build & Test"

    strategy:
      fail-fast: false
      matrix:
        resolver:
          - "stack-lts16"
          - "stack"
        servant-server-flag: # on by default
          - ""
          - "--flag servant-rate-limit:-server"
        servant-client-flag: # on by default
          - ""
          - "--flag servant-rate-limit:-client"

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v5

      - name: "Install Stack"
        uses: haskell-actions/setup@v2
        id: install-haskell
        with:
          stack-no-global: true
          enable-stack: true
          stack-setup-ghc: true
          stack-version: "latest"

      - name: "Initialise stack.yaml for latest resolver"
        if: matrix.resolver == 'stack'
        shell: bash
        run: stack init --resolver=lts-24

      - name: Write flags to file (for hashing)
        run: |
          echo ${{ matrix.servant-server-flag }} >> .cabal-flags
          echo ${{ matrix.servant-client-flag }} >> .cabal-flags
          cat .cabal-flags

      - name: Cache .stack
        id: cache-stack
        uses: actions/cache@v5
        with:
          path: ${{ steps.install-haskell.outputs.stack-root }}
          key: ${{ runner.os }}-${{ matrix.resolver }}-${{ hashFiles(format('{0}.yaml', matrix.resolver)) }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('.cabal-flags') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.resolver }}-${{ hashFiles(format('{0}.yaml', matrix.resolver)) }}-${{ hashFiles('**/*.cabal') }}-
            ${{ runner.os }}-${{ matrix.resolver }}-${{ hashFiles(format('{0}.yaml', matrix.resolver)) }}-
            ${{ runner.os }}-${{ matrix.resolver }}-

      - name: Install dependencies
        run: |
          stack --stack-yaml=${{ matrix.resolver }}.yaml --no-terminal build \
            ${{ matrix.servant-server-flag }} \
            ${{ matrix.servant-client-flag }} \
            --only-dependencies --fast

      - name: Build
        id: build
        run: |
          stack --stack-yaml=${{ matrix.resolver }}.yaml --no-terminal build \
            ${{ matrix.servant-server-flag }} \
            ${{ matrix.servant-client-flag }} \
            --fast --test --no-run-tests

      - name: Test
        id: test
        run: |
          docker compose up -d
          stack --stack-yaml=${{ matrix.resolver }}.yaml --no-terminal test \
            ${{ matrix.servant-server-flag }} \
            ${{ matrix.servant-client-flag }} \
            --fast
          docker compose down
