name: "Stackage Nightly"

on:
  workflow_dispatch:
  schedule:
    - cron: "5 6 * * *"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/stackage-nightly.yml"
  pull_request:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: write

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v5

      - name: Start containers
        shell: bash
        run: docker compose up -d

      - name: Build with the nightly snapshot
        uses: mbg/actions/stack/nightly@v0.3

      - name: Stop containers
        shell: bash
        run: docker compose down
